source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.4.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.1.0'
gem 'base64'
gem 'bigdecimal'
gem 'logger'
gem 'mutex_m'
gem 'ostruct'
# Use Puma as the app server
gem 'puma', '~> 6.0'

# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Use JavaScript with ESM import maps
gem 'importmap-rails'
