name: Push Buildpackage

on:
  release:
    types: [published]

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - name: Download
      id: download
      uses: paketo-buildpacks/github-config/actions/buildpackage/download@master
    - name: Push
      env:
        GCR_PUSH_BOT_JSON_KEY: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
      run: |
        echo "${GCR_PUSH_BOT_JSON_KEY}" | docker login --username _json_key --password-stdin gcr.io
        mkdir -p "${HOME}/tmp"
        skopeo --tmpdir "${HOME}/tmp" copy "oci-archive:${GITHUB_WORKSPACE}/${{ steps.download.outputs.buildpackage }}" "docker://gcr.io/${{ github.repository }}:${{ steps.download.outputs.tag }}"
        skopeo --tmpdir "${HOME}/tmp" copy "oci-archive:${GITHUB_WORKSPACE}/${{ steps.download.outputs.buildpackage }}" "docker://gcr.io/${{ github.repository }}:latest"
