name: Push Buildpackage

on:
  release:
    types: [published]

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - name: Download
      id: download
      uses: paketo-buildpacks/github-config/actions/buildpackage/download@gcr-push
    - name: Push
      run: |
        docker login --username _json_key --password "${{ secrets.GCR_PUSH_BOT_JSON_KEY }}" gcr.io
        docker import image "${GITHUB_WORKSPACE}/${{ steps.download.outputs.buildpackage }}" "gcr.io/${{ github.repository }}:${{ steps.download.outputs.tag }}"
        docker push "gcr.io/${{ github.repository }}:${{ steps.download.outputs.tag }}"
